/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ProfileIdLazyImport = createFileRoute('/$profileId')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ProfileIdLazyRoute = ProfileIdLazyImport.update({
  id: '/$profileId',
  path: '/$profileId',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/$profileId.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/$profileId': {
      id: '/$profileId'
      path: '/$profileId'
      fullPath: '/$profileId'
      preLoaderRoute: typeof ProfileIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/$profileId': typeof ProfileIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/$profileId': typeof ProfileIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/$profileId': typeof ProfileIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$profileId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$profileId'
  id: '__root__' | '/' | '/$profileId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ProfileIdLazyRoute: typeof ProfileIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ProfileIdLazyRoute: ProfileIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$profileId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/$profileId": {
      "filePath": "$profileId.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
