apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sepolia
  namespace: enstate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-sepolia
  template:
    metadata:
      labels:
        app: redis-sepolia
    spec:
      containers:
        - name: redis-sepolia
          image: redis:6.0.9-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sepolia
  namespace: enstate
spec:
  selector:
    app: redis-sepolia
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enstate-sepolia
  namespace: enstate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enstate-sepolia
  template:
    metadata:
      labels:
        app: enstate-sepolia
    spec:
      containers:
        - name: enstate-sepolia
          image: ghcr.io/v3xlabs/enstate:edge
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: OPENSEA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: opensea-api-key
                  key: api-key
            - name: REDIS_URL
              value: redis://redis-sepolia.enstate.svc.cluster.local:6379
            - name: RPC_URL
              value: https://rpc.ankr.com/eth_sepolia,https://ethereum-sepolia.publicnode.com,https://sepolia.gateway.tenderly.co
            - name: UNIVERSAL_RESOLVER
              value: "0xBaBC7678D7A63104f1658c11D6AE9A21cdA09725"
            - name: IPFS_GATEWAY
              value: https://cloudflare-ipfs.com/ipfs/
            - name: OTLP_ENDPOINT
              value: http://tempo-enstate-tempo-distributor:4317
            - name: OTLP_LABEL
              value: enstate-sepolia
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: enstate-sepolia
  namespace: enstate
spec:
  selector:
    app: enstate-sepolia
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enstate-sepolia
  namespace: enstate
  annotations:
    cert-manager.io/issuer: le-http
spec:
  ingressClassName: traefik
  rules:
    - host: sepolia.enstate.rs
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: enstate-sepolia
                port:
                  number: 3000
  tls:
  - hosts:
    - sepolia.enstate.rs
    secretName: tls-sepolia-enstate-ingress-http
