apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-goerli
  namespace: enstate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-goerli
  template:
    metadata:
      labels:
        app: redis-goerli
    spec:
      containers:
        - name: redis-goerli
          image: redis:6.0.9-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-goerli
  namespace: enstate
spec:
  selector:
    app: redis-goerli
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enstate-goerli
  namespace: enstate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: enstate-goerli
  template:
    metadata:
      labels:
        app: enstate-goerli
    spec:
      containers:
        - name: enstate-goerli
          image: ghcr.io/v3xlabs/enstate:1.0.4-1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: OPENSEA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: opensea-api-key
                  key: api-key
            - name: REDIS_URL
              value: redis://redis-goerli.enstate.svc.cluster.local:6379
            - name: RPC_URL
              value: https://rpc.ankr.com/eth_goerli,https://goerli.blockpi.network/v1/rpc/public,https://ethereum-goerli.publicnode.com
            - name: UNIVERSAL_RESOLVER
              value: 0xfc4AC75C46C914aF5892d6d3eFFcebD7917293F1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: enstate-goerli
  namespace: enstate
spec:
  selector:
    app: enstate-goerli
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enstate-goerli
  namespace: enstate
  annotations:
    cert-manager.io/issuer: le-http
spec:
  ingressClassName: traefik
  rules:
    - host: goerli.enstate.rs
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: enstate-goerli
                port:
                  number: 3000
  tls:
  - hosts:
    - goerli.enstate.rs
    secretName: tls-goerli-enstate-ingress-http
