on:
  workflow_call:

jobs:
  build:
    name: Build ENState 🚀
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2

      - run: cargo build --release
        working-directory: server
